# Generated by Django 4.2.23 on 2025-08-18 15:37

from decimal import Decimal
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("logo_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Метод оплаты",
                "verbose_name_plural": "Методы оплаты",
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("tg_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("language", models.CharField(default="ru", max_length=10)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("last_free_check", models.DateTimeField(blank=True, null=True)),
                (
                    "referral_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("referrer_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
            },
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("admin_login", "Вход администратора"),
                    ("user_block", "Блокировка пользователя"),
                    ("user_unblock", "Разблокировка пользователя"),
                    ("balance_change", "Изменение баланса"),
                    ("message_send", "Отправка сообщения"),
                    ("text_edit", "Редактирование текста"),
                    ("admin_create", "Создание администратора"),
                    ("admin_delete", "Удаление администратора"),
                    ("system_restart", "Перезапуск системы"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Текст",
                "verbose_name_plural": "Тексты",
                "db_table": "texts",
                "unique_together": {("lang", "key")},
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("invited_id", models.BigIntegerField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("balance", "Баланс"),
                            ("free_check", "Бесплатная проверка"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферал",
                "verbose_name_plural": "Рефералы",
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("binance", "Binance Pay"),
                            ("crypto", "Crypto"),
                            ("card", "Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tx_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исходящее сообщение",
                "verbose_name_plural": "Исходящие сообщения",
                "db_table": "outbox",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=255)),
                ("chain", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[("free", "Бесплатная"), ("paid", "Платная")],
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка",
                "verbose_name_plural": "Проверки",
                "db_table": "checks",
            },
        ),
    ]
