# Generated by Django 4.2.23 on 2025-08-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_paymentmethod_setting_user_alter_adminuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("admin_login", "Вход администратора"),
                    ("admin_logout", "Выход администратора"),
                    ("user_block", "Блокировка пользователя"),
                    ("user_unblock", "Разблокировка пользователя"),
                    ("balance_change", "Изменение баланса"),
                    ("personal_message_send", "Отправка персонального сообщения"),
                    ("mass_message_send", "Отправка массового сообщения"),
                    ("text_edit", "Редактирование текста"),
                    ("admin_create", "Создание администратора"),
                    ("admin_delete", "Удаление администратора"),
                    ("system_restart", "Перезапуск системы"),
                    ("user_view", "Просмотр профиля пользователя"),
                    ("user_activity_view", "Просмотр активности пользователя"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("personal", "Персональное сообщение"),
                            ("mass", "Массовая рассылка"),
                            ("system", "Системное сообщение"),
                            ("support", "Поддержка"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("language", models.CharField(default="ru", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("sent", "Отправлено"),
                            ("delivered", "Доставлено"),
                            ("read", "Прочитано"),
                            ("failed", "Ошибка отправки"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mass_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_messages",
                        to="core.massmessage",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_user_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение пользователю",
                "verbose_name_plural": "Сообщения пользователям",
                "db_table": "user_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="user_messag_user_id_9a6e1b_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="user_messag_status_fc945a_idx",
                    ),
                    models.Index(
                        fields=["message_type", "created_at"],
                        name="user_messag_message_553c77_idx",
                    ),
                ],
            },
        ),
    ]
