# Generated by Django 4.2.23 on 2025-08-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_is_blocked_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bottext",
            options={
                "ordering": ["category", "language", "-version"],
                "verbose_name": "Текст бота",
                "verbose_name_plural": "Тексты бота",
            },
        ),
        # Удаляем старое уникальное ограничение если оно существует
        migrations.RunSQL(
            "DROP INDEX IF EXISTS core_bottext_text_type_language_version_uniq;",
            reverse_sql=""
        ),
        migrations.AddField(
            model_name="bottext",
            name="category",
            field=models.CharField(
                choices=[
                    ("welcome", "Приветственные сообщения"),
                    ("main_menu", "Главное меню"),
                    ("check", "Сообщения проверки"),
                    ("check_choice", "Выбор типа проверки"),
                    ("check_result", "Результат проверки"),
                    ("payment", "Платежные сообщения"),
                    ("error", "Сообщения об ошибках"),
                    ("help", "Справка и помощь"),
                    ("settings", "Настройки"),
                    ("insufficient_balance", "Недостаточно средств"),
                    ("user_blocked", "Пользователь заблокирован"),
                ],
                default="welcome",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bottext",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_texts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bottext",
            unique_together={("category", "language", "version")},
        ),
        migrations.RemoveField(
            model_name="bottext",
            name="text_type",
        ),
    ]
