# Generated by Django 4.2.23 on 2025-08-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bottext_options_alter_bottext_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmessage',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.RenameField(
            model_name='massmessage',
            old_name='is_active',
            new_name='is_active_only',
        ),
        migrations.AddField(
            model_name='massmessage',
            name='user_filter',
            field=models.CharField(blank=True, default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='massmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massmessage',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('SCHEDULED', 'Запланировано'), ('SENDING', 'Отправляется'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('FAILED', 'Ошибка')], default='DRAFT', max_length=20),
        ),
    ]
