# Generated by Django 4.2.23 on 2025-08-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_massmessage_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassSendSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'Выполняется'), ('PAUSED', 'Приостановлено'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('batch_size', models.IntegerField(default=50)),
                ('delay_between_batches', models.IntegerField(default=1)),
                ('delay_between_messages', models.FloatField(default=0.1)),
                ('max_retries', models.IntegerField(default=3)),
                ('current_retry', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_sessions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_sessions', to='core.massmessage')),
            ],
            options={
                'verbose_name': 'Сессия рассылки',
                'verbose_name_plural': 'Сессии рассылки',
                'db_table': 'mass_send_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MassSendRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка'), ('SKIPPED', 'Пропущено'), ('BLOCKED', 'Заблокирован')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.masssendsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_send_recipients', to='core.user')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'db_table': 'mass_send_recipients',
                'ordering': ['created_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
