"""add_mass_messaging_tables

Revision ID: 9701551ba0c4
Revises: 5bb1186edd4c
Create Date: 2025-08-20 11:14:47.714020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9701551ba0c4'
down_revision = '5bb1186edd4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mass_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='massmessagestatus'), nullable=False),
    sa.Column('min_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_language', sa.String(length=10), nullable=True),
    sa.Column('is_active_only', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mass_message_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mass_message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='outboxstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mass_message_id'], ['mass_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_table('mass_message_recipients')
    op.drop_table('mass_messages')
    # ### end Alembic commands ###
